CREATE TEMPORARY DATABASE SAI; -- SQL compilation error: syntax error line 1 at position 17 unexpected 'DATABASE'.
CREATE TRANSIENT DATABASE SAI;

CREATE or replace DATABASE SAI; -- SQL compilation error: Object 'SAI' already exists

CREATE DATABASE SAI1; -- Database SAI1 successfully created.
DROP DATABASE SAI;

--------------------------------------------------SCHEMA---------------------------------------------------------------
CREATE TEMPORARY SCHEMA SAI_SCHEMA; --Unsupported feature 'TEMPORARY SCHEMA'.
CREATE or replace TRANSIENT SCHEMA SAI_SCHEMA; --Schema SAI_SCHEMA successfully created.
CREATE or replace SCHEMA SAI_SCHEMA; --SQL compilation error: Object 'SAI_SCHEMA' already exists.

---------------------------------TABLES-----------------------------------------------------------------------------
CREATE TEMPORARY TABLE SAI1(EMPID INT,EMPNAME VARCHAR(30),EMPROLE VARCHAR(30)); 
CREATE TRANSIENT TABLE SAI1(EMPID INT,EMPNAME VARCHAR(30),EMPROLE VARCHAR(30));
CREATE TABLE SAI1(EMPID INT,EMPNAME VARCHAR(30),EMPROLE VARCHAR(30));
DROP TEMPORARY TABLE SAI1;
SHOW SCHEMAS;
-- DATABASES CAN BE CREATED AS TRANSIENT AND PERMANENT
-- SCHEMAS CAN BE CREATED AS TRANSIENT AND PERMANENT
-- TABLES CAN BE CREATED AS TRANSIENT, PERMANENT AND TEMPORARY

-- IN TRANSIENT DATABASE WE CAN CREATE TRANSIENT SCHEMA AND TRANSIENT TABLES, PERMANENT TABLES
-- IN TRANSIENT SCHEMA WE CAN CREATE TRANSIENT TABLES, PERMANENT TABLES
-- IN PERMANENT DATABASE WE CAN CREATE PERMANENT SCHEMA, TRANSIENT SCHEMA AND PERMANENT TABLES, TRANSIENT TABLES, PERMANENT TABLES

-- BY DEFAULT ALL TABLES DATA_RETENTION_TIME_IN_DAYS = 1
-- TRANSIENT AND TEMPORARY DATA_RETENTION_TIME_IN_DAYS CAN BE SET FROM 0 TO 1
-- PERMANENT DATA_RETENTION_TIME_IN_DAYS CAN BE SET TO 0 T0 90 DAYS
